/****************************************************************************
 * arch/arm/src/imxrt/hardware/rt118x/imxrt118x_ocotp.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_OCOTP_H
#define __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_OCOTP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "hardware/imxrt_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Generated from NXP MIMXRT1186_cm33.xml (SVD). */

/* OCOTP_FSB Register Offsets (base IMXRT_OCOTP_BASE = 0x47518000) */

#define IMXRT_OCOTP_OTP_SHADOW_PARTA_OFFSET(n) (0x0000 + ((unsigned)(n) * 4))  /* OTP shadow register x52 */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB312_OFFSET 0x04e0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB313_OFFSET 0x04e4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB314_OFFSET 0x04e8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB315_OFFSET 0x04ec  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB316_OFFSET 0x04f0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB317_OFFSET 0x04f4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB318_OFFSET 0x04f8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB319_OFFSET 0x04fc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB320_OFFSET 0x0500  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB321_OFFSET 0x0504  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB322_OFFSET 0x0508  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB323_OFFSET 0x050c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB324_OFFSET 0x0510  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB325_OFFSET 0x0514  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB326_OFFSET 0x0518  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB327_OFFSET 0x051c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB328_OFFSET 0x0520  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB329_OFFSET 0x0524  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB330_OFFSET 0x0528  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB331_OFFSET 0x052c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB332_OFFSET 0x0530  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB333_OFFSET 0x0534  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB334_OFFSET 0x0538  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB335_OFFSET 0x053c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB336_OFFSET 0x0540  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB337_OFFSET 0x0544  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB338_OFFSET 0x0548  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB339_OFFSET 0x054c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB340_OFFSET 0x0550  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB341_OFFSET 0x0554  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB342_OFFSET 0x0558  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB343_OFFSET 0x055c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB344_OFFSET 0x0560  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB345_OFFSET 0x0564  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB346_OFFSET 0x0568  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB347_OFFSET 0x056c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB348_OFFSET 0x0570  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB349_OFFSET 0x0574  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB350_OFFSET 0x0578  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB351_OFFSET 0x057c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB352_OFFSET 0x0580  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB353_OFFSET 0x0584  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB354_OFFSET 0x0588  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB355_OFFSET 0x058c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB356_OFFSET 0x0590  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB357_OFFSET 0x0594  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB358_OFFSET 0x0598  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB359_OFFSET 0x059c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB360_OFFSET 0x05a0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB361_OFFSET 0x05a4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB362_OFFSET 0x05a8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB363_OFFSET 0x05ac  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB364_OFFSET 0x05b0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB365_OFFSET 0x05b4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB366_OFFSET 0x05b8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB367_OFFSET 0x05bc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB368_OFFSET 0x05c0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB369_OFFSET 0x05c4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB370_OFFSET 0x05c8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB371_OFFSET 0x05cc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB372_OFFSET 0x05d0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB373_OFFSET 0x05d4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB374_OFFSET 0x05d8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB375_OFFSET 0x05dc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB376_OFFSET 0x05e0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB377_OFFSET 0x05e4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB378_OFFSET 0x05e8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB379_OFFSET 0x05ec  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB380_OFFSET 0x05f0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB381_OFFSET 0x05f4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB382_OFFSET 0x05f8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB383_OFFSET 0x05fc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB384_OFFSET 0x0600  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB385_OFFSET 0x0604  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB386_OFFSET 0x0608  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB387_OFFSET 0x060c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB388_OFFSET 0x0610  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB389_OFFSET 0x0614  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB390_OFFSET 0x0618  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB391_OFFSET 0x061c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB392_OFFSET 0x0620  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB393_OFFSET 0x0624  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB394_OFFSET 0x0628  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB395_OFFSET 0x062c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB396_OFFSET 0x0630  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB397_OFFSET 0x0634  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB398_OFFSET 0x0638  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB399_OFFSET 0x063c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB400_OFFSET 0x0640  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB401_OFFSET 0x0644  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB402_OFFSET 0x0648  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB403_OFFSET 0x064c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB404_OFFSET 0x0650  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB405_OFFSET 0x0654  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB406_OFFSET 0x0658  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB407_OFFSET 0x065c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB408_OFFSET 0x0660  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB409_OFFSET 0x0664  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB410_OFFSET 0x0668  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB411_OFFSET 0x066c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB412_OFFSET 0x0670  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB413_OFFSET 0x0674  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB414_OFFSET 0x0678  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB415_OFFSET 0x067c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB416_OFFSET 0x0680  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB417_OFFSET 0x0684  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB418_OFFSET 0x0688  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB419_OFFSET 0x068c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB420_OFFSET 0x0690  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB421_OFFSET 0x0694  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB422_OFFSET 0x0698  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB423_OFFSET 0x069c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB424_OFFSET 0x06a0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB425_OFFSET 0x06a4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB426_OFFSET 0x06a8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB427_OFFSET 0x06ac  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB428_OFFSET 0x06b0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB429_OFFSET 0x06b4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB430_OFFSET 0x06b8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB431_OFFSET 0x06bc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB432_OFFSET 0x06c0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB433_OFFSET 0x06c4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB434_OFFSET 0x06c8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB435_OFFSET 0x06cc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB436_OFFSET 0x06d0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB437_OFFSET 0x06d4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB438_OFFSET 0x06d8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB439_OFFSET 0x06dc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB440_OFFSET 0x06e0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB441_OFFSET 0x06e4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB442_OFFSET 0x06e8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB443_OFFSET 0x06ec  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB444_OFFSET 0x06f0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB445_OFFSET 0x06f4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB446_OFFSET 0x06f8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB447_OFFSET 0x06fc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB448_OFFSET 0x0700  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB449_OFFSET 0x0704  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB450_OFFSET 0x0708  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB451_OFFSET 0x070c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB452_OFFSET 0x0710  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB453_OFFSET 0x0714  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB454_OFFSET 0x0718  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB455_OFFSET 0x071c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB456_OFFSET 0x0720  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB457_OFFSET 0x0724  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB458_OFFSET 0x0728  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB459_OFFSET 0x072c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB460_OFFSET 0x0730  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB461_OFFSET 0x0734  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB462_OFFSET 0x0738  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB463_OFFSET 0x073c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB464_OFFSET 0x0740  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB465_OFFSET 0x0744  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB466_OFFSET 0x0748  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB467_OFFSET 0x074c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB468_OFFSET 0x0750  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB469_OFFSET 0x0754  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB470_OFFSET 0x0758  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB471_OFFSET 0x075c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB472_OFFSET 0x0760  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB473_OFFSET 0x0764  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB474_OFFSET 0x0768  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB475_OFFSET 0x076c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB476_OFFSET 0x0770  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB477_OFFSET 0x0774  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB478_OFFSET 0x0778  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB479_OFFSET 0x077c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB480_OFFSET 0x0780  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB481_OFFSET 0x0784  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB482_OFFSET 0x0788  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB483_OFFSET 0x078c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB484_OFFSET 0x0790  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB485_OFFSET 0x0794  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB486_OFFSET 0x0798  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB487_OFFSET 0x079c  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB488_OFFSET 0x07a0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB489_OFFSET 0x07a4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB490_OFFSET 0x07a8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB491_OFFSET 0x07ac  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB492_OFFSET 0x07b0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB493_OFFSET 0x07b4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB494_OFFSET 0x07b8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB495_OFFSET 0x07bc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB496_OFFSET 0x07c0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB497_OFFSET 0x07c4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB498_OFFSET 0x07c8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB499_OFFSET 0x07cc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB500_OFFSET 0x07d0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB501_OFFSET 0x07d4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB502_OFFSET 0x07d8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB503_OFFSET 0x07dc  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB504_OFFSET 0x07e0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB505_OFFSET 0x07e4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB506_OFFSET 0x07e8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB507_OFFSET 0x07ec  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB508_OFFSET 0x07f0  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB509_OFFSET 0x07f4  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB510_OFFSET 0x07f8  /* OTP shadow register */
#define IMXRT_OCOTP_OTP_SHADOW_PARTB511_OFFSET 0x07fc  /* OTP shadow register */

/* OCOTP_FSB Register Addresses */

#define IMXRT_OCOTP_OTP_SHADOW_PARTA(n) (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTA_OFFSET(n))
#define IMXRT_OCOTP_OTP_SHADOW_PARTB312 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB312_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB313 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB313_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB314 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB314_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB315 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB315_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB316 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB316_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB317 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB317_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB318 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB318_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB319 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB319_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB320 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB320_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB321 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB321_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB322 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB322_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB323 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB323_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB324 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB324_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB325 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB325_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB326 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB326_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB327 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB327_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB328 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB328_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB329 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB329_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB330 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB330_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB331 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB331_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB332 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB332_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB333 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB333_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB334 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB334_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB335 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB335_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB336 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB336_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB337 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB337_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB338 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB338_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB339 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB339_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB340 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB340_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB341 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB341_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB342 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB342_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB343 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB343_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB344 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB344_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB345 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB345_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB346 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB346_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB347 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB347_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB348 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB348_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB349 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB349_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB350 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB350_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB351 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB351_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB352 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB352_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB353 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB353_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB354 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB354_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB355 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB355_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB356 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB356_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB357 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB357_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB358 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB358_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB359 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB359_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB360 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB360_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB361 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB361_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB362 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB362_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB363 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB363_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB364 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB364_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB365 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB365_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB366 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB366_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB367 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB367_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB368 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB368_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB369 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB369_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB370 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB370_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB371 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB371_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB372 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB372_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB373 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB373_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB374 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB374_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB375 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB375_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB376 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB376_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB377 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB377_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB378 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB378_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB379 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB379_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB380 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB380_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB381 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB381_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB382 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB382_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB383 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB383_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB384 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB384_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB385 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB385_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB386 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB386_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB387 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB387_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB388 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB388_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB389 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB389_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB390 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB390_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB391 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB391_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB392 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB392_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB393 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB393_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB394 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB394_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB395 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB395_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB396 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB396_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB397 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB397_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB398 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB398_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB399 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB399_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB400 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB400_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB401 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB401_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB402 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB402_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB403 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB403_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB404 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB404_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB405 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB405_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB406 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB406_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB407 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB407_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB408 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB408_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB409 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB409_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB410 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB410_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB411 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB411_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB412 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB412_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB413 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB413_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB414 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB414_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB415 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB415_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB416 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB416_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB417 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB417_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB418 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB418_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB419 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB419_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB420 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB420_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB421 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB421_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB422 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB422_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB423 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB423_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB424 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB424_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB425 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB425_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB426 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB426_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB427 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB427_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB428 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB428_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB429 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB429_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB430 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB430_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB431 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB431_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB432 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB432_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB433 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB433_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB434 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB434_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB435 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB435_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB436 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB436_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB437 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB437_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB438 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB438_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB439 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB439_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB440 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB440_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB441 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB441_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB442 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB442_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB443 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB443_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB444 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB444_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB445 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB445_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB446 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB446_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB447 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB447_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB448 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB448_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB449 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB449_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB450 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB450_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB451 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB451_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB452 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB452_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB453 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB453_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB454 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB454_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB455 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB455_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB456 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB456_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB457 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB457_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB458 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB458_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB459 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB459_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB460 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB460_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB461 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB461_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB462 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB462_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB463 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB463_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB464 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB464_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB465 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB465_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB466 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB466_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB467 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB467_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB468 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB468_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB469 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB469_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB470 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB470_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB471 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB471_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB472 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB472_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB473 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB473_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB474 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB474_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB475 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB475_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB476 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB476_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB477 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB477_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB478 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB478_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB479 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB479_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB480 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB480_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB481 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB481_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB482 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB482_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB483 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB483_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB484 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB484_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB485 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB485_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB486 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB486_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB487 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB487_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB488 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB488_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB489 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB489_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB490 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB490_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB491 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB491_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB492 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB492_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB493 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB493_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB494 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB494_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB495 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB495_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB496 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB496_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB497 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB497_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB498 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB498_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB499 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB499_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB500 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB500_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB501 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB501_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB502 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB502_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB503 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB503_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB504 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB504_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB505 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB505_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB506 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB506_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB507 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB507_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB508 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB508_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB509 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB509_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB510 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB510_OFFSET)
#define IMXRT_OCOTP_OTP_SHADOW_PARTB511 (IMXRT_OCOTP_BASE + IMXRT_OCOTP_OTP_SHADOW_PARTB511_OFFSET)

#endif /* __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_OCOTP_H */
